
export const GET_PRODUCTS = '[PRODUCT] GET PRODUCTS'

export const ADD_TO_CART = '[CART] ADD TO CART'

export const GET_CARTS = '[CART] GET CARTS'

export const DELETE_CART_BY_ID = '[CART] DELETE CART BY ID'

export const ADD_QTY_BY_ID = '[CART] ADD QTY CART BY ID'
export const REMOVE_QTY_BY_ID = '[CART] REMOVE QTY CART BY ID'